owner: cfm-miku-en
repo: uptime

sites:
  - name: Website and API
    url: https://delta.mikuuu.xyz/api/v2/changelog
  - name: Multiplayer
    url: https://delta.mikuuu.xyz/signalr/multiplayer/negotiate
    expectedStatusCodes:
      - 401
  - name: Spectator
    url: https://delta.mikuuu.xyz/signalr/spectator/negotiate
    expectedStatusCodes:
      - 401
  - name: Beatmap downloads (catboy.best)
    url: https://catboy.best/api/v2/s/1
  - name: Beatmap downloads (osu.direct)
    url: https://osu.direct/api/v2/s/1

status-website:
  cname: status.mikuuu.xyz
  name: deltalazer status
  introTitle: deltalazer server status
  introMessage: Live status of the deltalazer servers and the beatmap mirrors they use.
  navbar:
    - title: Status
      href: /
    - title: deltalazer
      href: https://delta.mikuuu.xyz
